### ISSUE TITLE
[Feature Request] MPRIS support

### ISSUE THREAD

**Issue by Merlin04** [Nokse22/high-tide#1]
Super cool project, very glad to have a nice Tidal client that isn't an electron app :) It would be awesome if it had support for MPRIS so I can use global desktop environment shortcuts to play/pause playback!

**Comment by Nokse22** [comment]
Hi, it is something I want to add, but I need to figure out how... :)

**Comment by Suzamax** [comment]
https://specifications.freedesktop.org/mpris-spec/latest/ check this out!

 Great app tbh, basics do work as expected. Still unfinished, but I like it ;) also, snek :D

**Comment by Nokse22** [comment]
I've started to implement it, still need to do some work
