### ISSUE TITLE
Queue always repeats

### ISSUE THREAD

**Issue by Drakulix** [Nokse22/high-tide#11]
Playing an album through will cause it to start again without an option to disable that behaviour.

Maybe this could be configurable in settings? Happy to tackle this, if given some pointers. :)

(Thanks for working on this!)

**Comment by Nokse22** [comment]
Hello! Thank you.
It should be the button opposite to the shuffle in the controls, but I've never implemented it. It should function as a repeat song/album/once with different icons that represents each state.

All the player logic is handled in `src/lib/player_object.py`, so here you would need to add the repeat logic. In `src/window.py` you would need to add a handler for when `repeat_button` is clicked and change the state in the `player_object` and the icon accordingly, now the repeat_button is a toggle button, but it would need to be a normal button. 

For the logic you would need to handle it in the `play_next` function in `player_object.py`.
If the state is repeat once it should stop at the end of the album, if it is repeat song it will  start the song over, if it's repeat album it is the current behavior.

It would be also good to save the preferred state between restarts.

Let me know if you need help. If you end up not doing it is fine.

**Comment by Nokse22** [comment]
I have fixed this. Sorry it took me a while, but working on something based on a proprietary service is not always stimulating. :sweat_smile:
