### ISSUE TITLE
[Feature] PKCE authentication

### ISSUE THREAD

**Issue by GioF71** [Nokse22/high-tide#5]
Hello, would it be possible to implement the pkce authentication, so that we can have access to hi-res playback up to 24bit/192kHz?
That would be complementary to my previous issue #4.

Thank you

**Comment by Nokse22** [comment]
Regarding pkce authentication I think python-tidal supports it and I could try to add it, if someone wants to contribute they are welcome.

**Comment by GioF71** [comment]
Hello, I have implemented it in my tidal plugin for upmpdcli so maybe I can help you. I will have a look at the code.
Thank you!

**Comment by GioF71** [comment]
Hello, this is not needed anymore. Even in the tidal plugin for upmpdcli, I dropped this kind of authentication as we can access HI_RES_LOSSLESS using the "normal" oauth authentication flow.
