### ISSUE TITLE
Sidebar content diappears when playing a song from tracks

### ISSUE THREAD

**Issue by BadgerInATrenchcoat** [Nokse22/high-tide#7]
First, I've been loving the application so far.  I've run into a couple hitches that I will report soon, but this is the app that I and others have been waiting for for years.  Fantastic work, my friend.  

**Expected behavior:**
When entering track list and playing a song, the rest of the UI stays consistent except for the playbar, track information, etc.

**Actual behavior: **
When clicking "Tracks" from the sidebar then playing a song from the listing, the entire sidebar goes blank.  It retains hover highlights, but there is no longer any text as can be seen in the screenshot below.  After clicking anywhere within this area, however, the original bar returns. Additionally, where you click within the sidebar while it is blank is the same place that you will be taken. For instance, if you click a where a playlist would have been, you will still be taken to that same playlist. 
 
![swappy-20240618-040012](https://github.com/Nokse22/high-tide/assets/169167220/a82c4697-ec0a-4992-80ac-a5f0214bc159)

**Comment by Nokse22** [comment]
Hello! Thank you so much.
That's a really strange behavior I have never encountered, but I might know what causes it.

It's very useful for me reporting anything else that doesn't work, so that I don't forget to fix it.

**Comment by pika-colony** [comment]
After observing this issue a few more times in regular use, I have noticed that it is not the cells going blank at all. Instead, it is the sidebar being automatically scrolled all the way to the right past the element titles. It seems the text area is scaling to be as wide as the longest playlist name, but not actually expanding the sidebar along with it. This causes the viewable area to be much thinner than the content area. That, along with the issue of it randomly and automatically snapping to the right/end of the text area causes the appearance of the elements going invisible. One solution would be to fix the text area to the same maximum width as the sidebar area, and truncate element text/titles that are longer than the available space.

**Comment by Nokse22** [comment]
Great, then it should be a very easy fix
