### ISSUE TITLE
Playing multiple tracks in quick succession freezes or blanks out whole window

### ISSUE THREAD

**Issue by BadgerInATrenchcoat** [Nokse22/high-tide#9]
**Expected Behavior:**
Playing multiple tracks back-to-back would simply play them back to back.

**Actual Behavior:** 
When clicking to play multiple tracks in quick succession, the player will often break and either show a frozen image of the player or blank out the screen altogether with the background color (as shown in the video below).  There is no consistent amount of clicks/plays it takes to cause this behavior. It will sometimes work fine for over a dozen tracks, and other times it will break in this way after only two or three quick track changes. Even when the application view is blanked out as shown in the video, however, I am still able to interact with parts of the application.  In the video linked below, for example, even after the application goes blank I am able to play other songs off the same album if I click in the area where those tracks would be on screen.

https://github.com/Nokse22/high-tide/assets/169167220/9dc5a023-599b-4619-b513-957f65a5c73b

**Comment by Nokse22** [comment]
I think this issue should be fixed
